// Ruling 44: writes src/voice/cities.ts, the world's big cities for the voice fast path (src/voice/match.ts): every
// place of 1 million people or more, and every capital, from GeoNames cities15000 (CC BY 4.0), the file the data build
// names places with. The matcher needs them because the dataset names a place after the town its stations sit in:
// Tokyo's stations are "Aoi", "Yokohama" and "Fujisawa", and "New York" is a one-station place upstate while the
// city's stations are "New York City". Districts (PPLX) and historical, abandoned or destroyed places are left out, as
// in scripts/lib/gazetteer.ts. Run it by hand after `npm run data` has cached the GeoNames file: `npm run cities`.
// The output is committed, so neither CI nor the nightly build needs the file for it.
import { readFileSync, writeFileSync } from 'node:fs';

const src = process.argv[2] ?? '.cache/cities15000.txt';
const EXCLUDED = new Set(['PPLX', 'PPLH', 'PPLQ', 'PPLW', 'PPLCH']);

const picked = readFileSync(src, 'utf8').split('\n')
  .map(line => line.split('\t'))
  .filter(f => f.length >= 18 && f[6] === 'P' && !EXCLUDED.has(f[7]) && (Number(f[14]) >= 1e6 || f[7] === 'PPLC'))
  .sort((a, b) => Number(b[14]) - Number(a[14]) || a[1].localeCompare(b[1]));

const entries = picked.map(f => {
  if (/[,;]/.test(f[1])) throw new Error(`separator in city name: ${f[1]}`);
  return [f[1], f[8], Math.round(Number(f[4]) * 10), Math.round(Number(f[5]) * 10)].join(',');
});

writeFileSync('src/voice/cities.ts', [
  `// Generated by scripts/make-cities.ts from GeoNames cities15000 (CC BY 4.0): ${entries.length} cities of 1 million people`,
  '// or more plus every capital, largest first, as "name,country,lat×10,lon×10" separated by ";". Do not edit.',
  `export const CITIES = ${JSON.stringify(entries.join(';'))};`,
  '',
].join('\n'));
console.log(`src/voice/cities.ts: ${entries.length} cities`);
